### PR TITLE
Fix use of Symfony 2.5 deprecated interface and method in ValidatorStep

### PR DESCRIPTION
**Pull request by ddeboer**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Errors fixed

**Comment by ddeboer** [comment]
Wait, I’m pushing to this PR too. :)

**Comment by sagikazarmark** [comment]
Sorry. I fixed test errors on the master branch.

**Comment by sagikazarmark** [comment]
I mean no symfony related errors. Other errors are fixed here. You might have to restart travis builds as I rebased the branch and force pushed it.

**Pull request merged**
